all_program: 07

01:	s_IGA_20220205.c
	gcc -o s_IGA_CGex.x s_IGA_20220205.c -O1 -lm -Wall -Wextra

02:	CholeskyDecomp.c
	gcc -o CholeskyDecomp.x CholeskyDecomp.c -O1 -lm -Wall

03: s_IGA_old.c
	gcc -o s_IGA_old.x s_IGA_old.c -O1 -lm -Wall

04:	s_IGA_20220317.c
	gcc -o s_IGA_CGex.x s_IGA_20220205.c -O1 -lm -Wall -Wextra

05:	s_IGA_PCGv3.c
	gcc -o s_IGA_PCGv3.x s_IGA_PCGv3.c -O1 -lm -Wall -Wextra

06:	s_IGA_PCGv4.c
	gcc -o s_IGA_PCGv4.x s_IGA_PCGv4.c -O1 -lm -Wall -Wextra

07:	IMM_PCGv1.c
	gcc -o IMM_PCGv1.x IMM_PCGv1.c -O1 -lm -Wall -Wextra