all_program: 04

01:	s_IGA_20220205.c
	gcc -o s_IGA_CGex.x s_IGA_20220205.c -O1 -lm -Wall -Wextra

02:	CholeskyDecomp.c
	gcc -o CholeskyDecomp.x CholeskyDecomp.c -O1 -lm -Wall

03: s_IGA_old.c
	gcc -o s_IGA_old.x s_IGA_old.c -O1 -lm -Wall

04:	s_IGA_20220317.c
	gcc -o s_IGA_CGex.x s_IGA_20220205.c -O1 -lm -Wall -Wextra